spring:
   profiles:
      active:
      - dev
---
spring:
   profiles: dev
   application:
      name: myspringcloud02-config-eureka-7001-dev

server:
   port: 8761

eureka:
   instance:
      hostname: myspringcloud02-eureka-8761.com
   client:
      register-with-eureka: false   #是否向注册中心注册自己
      fetch-registry: false   #是否从注册中心查询服务
      service-url:   #注册中心地址
         defaultZone: http://myspringcloud02-eureka-8762.com:8762/eureka/,http://myspringcloud02-eureka-8763.com:8763/eureka/
---
spring:
   profiles: test
   application:
      name: myspringcloud02-config-eureka-7001-test

server:
   port: 8761

eureka:
   instance:
      hostname: myspringcloud02-eureka-8761.com
   client:
      register-with-eureka: false   #是否向注册中心注册自己
      fetch-registry: false   #是否从注册中心查询服务
      service-url:   #注册中心地址
         defaultZone: http://myspringcloud02-eureka-8762.com:8762/eureka/,http://myspringcloud02-eureka-8763.com:8763/eureka/