server:
   port: 8081
   
feign: 
   hystrix: 
      enabled: true

eureka:
   client:
      register-with-eureka: false
      serviceUrl:
         #指定服务注册中心的地址
         defaultZone: http://myspringcloud02-eureka-8761.com:8761/eureka/,http://myspringcloud02-eureka-8762.com:8762/eureka/,http://myspringcloud02-eureka-8763.com:8763/eureka/