server: 
  port: 9527
 
spring: 
  application:
    name: myspringcloud02-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://myspringcloud02-eureka-8761.com:8761/eureka/,http://myspringcloud02-eureka-8762.com:8762/eureka/,http://myspringcloud02-eureka-8763.com:8763/eureka/  
  instance:
    instance-id: myspringcloud02-gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicecloud-dept
  prefix: /learning
  ignored-services: "*"
  routes: 
    mydept.serviceId: myspringcloud02-provider
    mydept.path: /myprovider/**
 
info:
  app.name: learning-microcloud
  company.name: www.learning.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

